In [39]:
import pandas as pd
d=pd.read_csv("Mobile_data.csv")

In [40]:
d.isnull().sum

<bound method DataFrame.sum of       Unnamed: 0  brand_name  model_name     os  popularity  best_price  \
0          False       False       False  False       False       False
1          False       False       False  False       False       False
2          False       False       False  False       False       False
3          False       False       False  False       False       False
4          False       False       False  False       False       False
...          ...         ...         ...    ...         ...         ...
1219       False       False       False  False       False       False
1220       False       False       False  False       False       False
1221       False       False       False  False       False       False
1222       False       False       False  False       False       False
1223       False       False       False   True       False       False

      lowest_price  highest_price  sellers_amount  screen_size  memory_size  \
0            False          False           False        False        False
1            False          False           False        False        False
2            False          False           False        False        False
3            False          False           False        False        False
4             True           True           False        False        False
...            ...            ...             ...          ...          ...
1219         False          False           False        False        False
1220         False          False           False        False        False
1221         False          False           False        False        False
1222         False          False           False        False        False
1223         False          False           False        False         True

      battery_size  release_date
0            False         False
1            False         False
2            False         False
3            False         False
4            False         False
...            ...           ...
1219         False         False
1220         False         False
1221         False         False
1222         False         False
1223         False         False

[1224 rows x 13 columns]>

In [41]:
d.duplicated().sum

<bound method Series.sum of 0       False
1       False
2       False
3       False
4       False
        ...
1219    False
1220    False
1221    False
1222    False
1223    False
Length: 1224, dtype: bool>

In [42]:
d.drop_duplicates()

,Unnamed: 0,brand_name,model_name,os,popularity,best_price,lowest_price,highest_price,sellers_amount,screen_size,memory_size,battery_size,release_date
0,0,ALCATEL,1 1/8GB Bluish Black (5033D-2JALUAA),Android,422,1690,1529.0,1819.0,36,5.00,8.0,2000.0,20-Oct
1,1,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,323,1803,1659.0,2489.0,36,5.00,16.0,2000.0,20-Sep
2,2,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,299,1803,1659.0,2489.0,36,5.00,16.0,2000.0,20-Sep
3,3,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,287,1803,1659.0,2489.0,36,5.00,16.0,2000.0,20-Sep
4,4,Nokia,1.3 1/16GB Charcoal,Android,1047,1999,NaN,NaN,10,5.71,16.0,3000.0,20-Apr
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1219,1219,Apple,iPhone XS Max 64GB Gold (MT522),iOS,1101,22685,16018.0,27900.0,61,6.50,64.0,3174.0,18-Sep
1220,1220,Apple,iPhone XS Max Dual Sim 64GB Gold (MT732),iOS,530,24600,21939.0,33720.0,28,6.50,64.0,3174.0,18-Sep
1221,1221,HUAWEI,nova 5T 6/128GB Black (51094MEU),Android,1174,8804,7999.0,9999.0,18,6.26,128.0,3750.0,19-Nov
1222,1222,ZTE,nubia Red Magic 5G 8/128GB Black,Android,752,18755,18500.0,19010.0,2,6.65,128.0,4500.0,20-Oct
1223,1223,Sigma mobile,x-style 35 Screen,NaN,952,907,785.0,944.0,75,3.50,NaN,1750.0,20-Jan

In [43]:
n=d.fillna(100)
n.info()

<class 'pandas.DataFrame'>
RangeIndex: 1224 entries, 0 to 1223
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      1224 non-null   int64
 1   brand_name      1224 non-null   str
 2   model_name      1224 non-null   str
 3   os              1224 non-null   object
 4   popularity      1224 non-null   int64
 5   best_price      1224 non-null   int64
 6   lowest_price    1224 non-null   float64
 7   highest_price   1224 non-null   float64
 8   sellers_amount  1224 non-null   int64
 9   screen_size     1224 non-null   float64
 10  memory_size     1224 non-null   float64
 11  battery_size    1224 non-null   float64
 12  release_date    1224 non-null   str
dtypes: float64(5), int64(4), object(1), str(3)
memory usage: 124.4+ KB

In [44]:
n.head()

,Unnamed: 0,brand_name,model_name,os,popularity,best_price,lowest_price,highest_price,sellers_amount,screen_size,memory_size,battery_size,release_date
0,0,ALCATEL,1 1/8GB Bluish Black (5033D-2JALUAA),Android,422,1690,1529.0,1819.0,36,5.00,8.0,2000.0,20-Oct
1,1,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,323,1803,1659.0,2489.0,36,5.00,16.0,2000.0,20-Sep
2,2,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,299,1803,1659.0,2489.0,36,5.00,16.0,2000.0,20-Sep
3,3,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,287,1803,1659.0,2489.0,36,5.00,16.0,2000.0,20-Sep
4,4,Nokia,1.3 1/16GB Charcoal,Android,1047,1999,100.0,100.0,10,5.71,16.0,3000.0,20-Apr

In [45]:
# x=d['highest_price'].mean()
# print(x)

In [46]:
# x=d['highest_price'].mean()
# n=d.fillna(x)
# n.head(10)

In [47]:
# d['highest_price']=d['highest_price'].mean()
d.head(10)

,Unnamed: 0,brand_name,model_name,os,popularity,best_price,lowest_price,highest_price,sellers_amount,screen_size,memory_size,battery_size,release_date
0,0,ALCATEL,1 1/8GB Bluish Black (5033D-2JALUAA),Android,422,1690,1529.0,1819.0,36,5.00,8.0,2000.0,20-Oct
1,1,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,323,1803,1659.0,2489.0,36,5.00,16.0,2000.0,20-Sep
2,2,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,299,1803,1659.0,2489.0,36,5.00,16.0,2000.0,20-Sep
3,3,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,287,1803,1659.0,2489.0,36,5.00,16.0,2000.0,20-Sep
4,4,Nokia,1.3 1/16GB Charcoal,Android,1047,1999,NaN,NaN,10,5.71,16.0,3000.0,20-Apr
5,5,Honor,10 6/64GB Black,Android,71,10865,10631.0,11099.0,2,5.80,64.0,3400.0,18-Jun
6,6,Honor,10 Lite 3/32GB Blue,Android,424,3999,NaN,NaN,2,6.21,32.0,3400.0,18-Dec
7,7,Honor,10 Lite 4/64GB Black,Android,134,4973,4733.0,5295.0,6,6.21,64.0,3400.0,19-Jan
8,8,Honor,10 lite 3/128GB Blue,Android,477,5100,4990.0,5222.0,3,6.21,128.0,3400.0,21-Jan
9,9,Honor,10 lite 3/64GB Black,Android,215,4948,4646.0,5372.0,8,6.21,64.0,3400.0,18-Dec

In [48]:
d['lowest_price']=d['lowest_price'].fillna(d.groupby('brand_name')['lowest_price'].transform('mean'))
d.head(10)
# x=d['lowest_price'].mean()
# print(x)
# d.info()

,Unnamed: 0,brand_name,model_name,os,popularity,best_price,lowest_price,highest_price,sellers_amount,screen_size,memory_size,battery_size,release_date
0,0,ALCATEL,1 1/8GB Bluish Black (5033D-2JALUAA),Android,422,1690,1529.000000,1819.0,36,5.00,8.0,2000.0,20-Oct
1,1,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,323,1803,1659.000000,2489.0,36,5.00,16.0,2000.0,20-Sep
2,2,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,299,1803,1659.000000,2489.0,36,5.00,16.0,2000.0,20-Sep
3,3,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,287,1803,1659.000000,2489.0,36,5.00,16.0,2000.0,20-Sep
4,4,Nokia,1.3 1/16GB Charcoal,Android,1047,1999,2676.368421,NaN,10,5.71,16.0,3000.0,20-Apr
5,5,Honor,10 6/64GB Black,Android,71,10865,10631.000000,11099.0,2,5.80,64.0,3400.0,18-Jun
6,6,Honor,10 Lite 3/32GB Blue,Android,424,3999,4913.684211,NaN,2,6.21,32.0,3400.0,18-Dec
7,7,Honor,10 Lite 4/64GB Black,Android,134,4973,4733.000000,5295.0,6,6.21,64.0,3400.0,19-Jan
8,8,Honor,10 lite 3/128GB Blue,Android,477,5100,4990.000000,5222.0,3,6.21,128.0,3400.0,21-Jan
9,9,Honor,10 lite 3/64GB Black,Android,215,4948,4646.000000,5372.0,8,6.21,64.0,3400.0,18-Dec

In [49]:
d['lowest_price']=d['lowest_price'].mean()
d.head()

,Unnamed: 0,brand_name,model_name,os,popularity,best_price,lowest_price,highest_price,sellers_amount,screen_size,memory_size,battery_size,release_date
0,0,ALCATEL,1 1/8GB Bluish Black (5033D-2JALUAA),Android,422,1690,7631.446981,1819.0,36,5.00,8.0,2000.0,20-Oct
1,1,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,323,1803,7631.446981,2489.0,36,5.00,16.0,2000.0,20-Sep
2,2,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,299,1803,7631.446981,2489.0,36,5.00,16.0,2000.0,20-Sep
3,3,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,287,1803,7631.446981,2489.0,36,5.00,16.0,2000.0,20-Sep
4,4,Nokia,1.3 1/16GB Charcoal,Android,1047,1999,7631.446981,NaN,10,5.71,16.0,3000.0,20-Apr

In [50]:
d.info()

<class 'pandas.DataFrame'>
RangeIndex: 1224 entries, 0 to 1223
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      1224 non-null   int64
 1   brand_name      1224 non-null   str
 2   model_name      1224 non-null   str
 3   os              1027 non-null   str
 4   popularity      1224 non-null   int64
 5   best_price      1224 non-null   int64
 6   lowest_price    1224 non-null   float64
 7   highest_price   964 non-null    float64
 8   sellers_amount  1224 non-null   int64
 9   screen_size     1222 non-null   float64
 10  memory_size     1112 non-null   float64
 11  battery_size    1214 non-null   float64
 12  release_date    1224 non-null   str
dtypes: float64(5), int64(4), str(4)
memory usage: 124.4 KB

In [51]:
d=d.dropna(subset=['os'])
d.info()

<class 'pandas.DataFrame'>
Index: 1027 entries, 0 to 1222
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      1027 non-null   int64
 1   brand_name      1027 non-null   str
 2   model_name      1027 non-null   str
 3   os              1027 non-null   str
 4   popularity      1027 non-null   int64
 5   best_price      1027 non-null   int64
 6   lowest_price    1027 non-null   float64
 7   highest_price   791 non-null    float64
 8   sellers_amount  1027 non-null   int64
 9   screen_size     1026 non-null   float64
 10  memory_size     1027 non-null   float64
 11  battery_size    1017 non-null   float64
 12  release_date    1027 non-null   str
dtypes: float64(5), int64(4), str(4)
memory usage: 112.3 KB

In [52]:
d=d.dropna(subset=['battery_size'])
d.info()

<class 'pandas.DataFrame'>
Index: 1017 entries, 0 to 1222
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      1017 non-null   int64
 1   brand_name      1017 non-null   str
 2   model_name      1017 non-null   str
 3   os              1017 non-null   str
 4   popularity      1017 non-null   int64
 5   best_price      1017 non-null   int64
 6   lowest_price    1017 non-null   float64
 7   highest_price   781 non-null    float64
 8   sellers_amount  1017 non-null   int64
 9   screen_size     1016 non-null   float64
 10  memory_size     1017 non-null   float64
 11  battery_size    1017 non-null   float64
 12  release_date    1017 non-null   str
dtypes: float64(5), int64(4), str(4)
memory usage: 111.2 KB

In [53]:
d=d.dropna(subset=['screen_size'])
d.info()

<class 'pandas.DataFrame'>
Index: 1016 entries, 0 to 1222
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      1016 non-null   int64
 1   brand_name      1016 non-null   str
 2   model_name      1016 non-null   str
 3   os              1016 non-null   str
 4   popularity      1016 non-null   int64
 5   best_price      1016 non-null   int64
 6   lowest_price    1016 non-null   float64
 7   highest_price   780 non-null    float64
 8   sellers_amount  1016 non-null   int64
 9   screen_size     1016 non-null   float64
 10  memory_size     1016 non-null   float64
 11  battery_size    1016 non-null   float64
 12  release_date    1016 non-null   str
dtypes: float64(5), int64(4), str(4)
memory usage: 111.1 KB

In [54]:
d['release_date']=pd.to_datetime(d['release_date'])
d.info()

<class 'pandas.DataFrame'>
Index: 1016 entries, 0 to 1222
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      1016 non-null   int64
 1   brand_name      1016 non-null   str
 2   model_name      1016 non-null   str
 3   os              1016 non-null   str
 4   popularity      1016 non-null   int64
 5   best_price      1016 non-null   int64
 6   lowest_price    1016 non-null   float64
 7   highest_price   780 non-null    float64
 8   sellers_amount  1016 non-null   int64
 9   screen_size     1016 non-null   float64
 10  memory_size     1016 non-null   float64
 11  battery_size    1016 non-null   float64
 12  release_date    1016 non-null   datetime64[us]
dtypes: datetime64[us](1), float64(5), int64(4), str(3)
memory usage: 111.1 KB

/tmp/ipykernel_5036/683925822.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  d['release_date']=pd.to_datetime(d['release_date'])

In [61]:
d=d.rename(columns={'release_date':'date'})
# d.info()
d.head()

,Unnamed: 0,brand_name,model_name,os,popularity,best_price,lowest_price,highest_price,sellers_amount,screen_size,memory_size,battery_size,date
0,0,ALCATEL,1 1/8GB Bluish Black (5033D-2JALUAA),Android,422,1690,7631.446981,1819.0,36,5.00,8.0,2000.0,1-10-20
1,1,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,323,1803,7631.446981,2489.0,36,5.00,16.0,2000.0,1-09-20
2,2,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,299,1803,7631.446981,2489.0,36,5.00,16.0,2000.0,1-09-20
3,3,ALCATEL,1 5033D 1/16GB Volcano Black (5033D-2LALUAF),Android,287,1803,7631.446981,2489.0,36,5.00,16.0,2000.0,1-09-20
4,4,Nokia,1.3 1/16GB Charcoal,Android,1047,1999,7631.446981,NaN,10,5.71,16.0,3000.0,1-04-20